version: '2.3'

services:
  mplabx:
    build:
     context: .
     dockerfile: Dockerfile
    environment:
     - DISPLAY
     - TZ=Europe/Oslo
    volumes:
     - /tmp/.X11-unix:/tmp/.X11-unix:ro
     - /dev/bus/usb:/dev/bus/usb
     - ./mplabx:/home/mplabx
    device_cgroup_rules:
     - 'c 189:* rmw'
    cap_drop:
     - ALL
    cap_add:
     - MKNOD
